### ISSUE TITLE
docker镜像大小为什么一下800多兆，一下2.3g，呀，是因为下载dl文件和其他临时文件吗？

### ISSUE THREAD

**Issue by aizhouyi** [SuLingGG/OpenWrt-Env#1]

**Comment by SuLingGG** [comment]
latest 标签的镜像是基础镜像，只安装了编译 OpenWrt 所需的依赖，所以只有 800M+ 。

其他超过 2G 的镜像是集成相应版本 OpenWrt 源码（官方/Lean/Project，详见我的 [OpenWrt-Rpi](https://github.com/SuLingGG/OpenWrt-Rpi) 项目） + 对应设备工具链 （Toolchain）的镜像，镜像内已预置了项目源码并且编译好了相应设备的工具链，拉取镜像直接使用，可以省去编译工具链的步骤，缩短 1 个小时左右的编译时间。

这些包含工具链的镜像也是由 GitHub Action 生成：
<https://github.com/SuLingGG/OpenWrt-Toolchain/actions>

Ps: 
之所以在 README.md 里没写这些是因为我懒...

**Comment by aizhouyi** [comment]
明白了，谢谢你的解答。
